version: "3"

services:
  # app:
  #   build: .
  #   depends_on:
  #     - db
  #   environment:
  #     NODE_ENV: production
  #     PORT: 8080
  #     DB_HOST: localhost
  #     DB_USER: root
  #     DB_PASS: root
  #     DB_NAME: ft

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ft
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql
    command: ["--sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"]

volumes:
  db-volume:
